databases:
  - name: portfolio_db
    databaseName: portfolio_db
    user: portfolio_user
    plan: free # optional

services:
  - type: web
    name: portfolio-site
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_site.wsgi:application"
    plan: free # optional
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CLOUDINARY_URL
        value: ""
